class Ticket < ApplicationRecord
  DEPARTMENTS = ['Accounting',
                 'City Court',
                 'Civil Service',
                 'City Council',
                 'Emergency Preparedness',
                 'Finance',
                 'Fire Department',
                 'Grants and Economic Dev.',
                 'Harang Jr. Municipal Auditorium',
                 'Housing and Community Dev.',
                 'Human Resources',
                 'Information Technology',
                 'Marketing and Public Relations',
                 'Office of the Mayor',
                 'Parks Department',
                 'Police Department',
                 'Public Works',
                 'Purchasing',
                 'Recreation Department',
                 'Senior Citizens Center',
                 'Sewer Treatment Plant',
                 'Tax, License, and Permits',
                 'Utilities',
                 'Water Plant']
end
